"""Meditation guide library with professional voice guidance and background music."""

from typing import Any

# ── Professional meditation guide library ──────────────────────────────────────
# Each guide includes:
# - voice_guidance: Structured script with timing (seconds) for voice narration
# - background_music: URL to calming background music track
# - total_duration: Total session length in seconds
# - difficulty_levels: Multiple versions for beginner, intermediate, advanced

MEDITATION_GUIDES: list[dict[str, Any]] = [
    # ── BREATHWORK ──────────────────────────────────────────────────────────────
    {
        "id": "breathwork-box-beginner",
        "title": "Box Breathing for Beginners",
        "description": "Simple equal-count breathing to calm the nervous system: 4-4-4-4.",
        "duration_minutes": 3,
        "category": "breathwork",
        "level": "beginner",
        "tags": ["anxiety", "quick", "stress-relief", "focus"],
        "thumbnail_url": "/images/meditation/breathwork-box.jpg",
        "background_music": "/audio/music/ambient-calm-180bpm.mp3",
        "voice_guidance": {
            "speaker": "Sofia - Warm, Soothing Female",
            "style": "gentle, encouraging",
            "total_duration_seconds": 180,
            "segments": [
                {"time": 0, "text": "Welcome to Box Breathing.", "duration": 3},
                {"time": 3, "text": "Find a comfortable seated position. Close your eyes when ready.", "duration": 4},
                {"time": 7, "text": "This technique balances your breath to calm your mind and body.", "duration": 4},
                {"time": 11, "text": "Inhale slowly through your nose for a count of four.", "duration": 4},
                {"time": 15, "text": "Hold your breath for a count of four.", "duration": 4},
                {"time": 19, "text": "Exhale slowly through your mouth for a count of four.", "duration": 4},
                {"time": 23, "text": "Hold empty for a count of four.", "duration": 4},
                {"time": 27, "text": "Ready? Let's begin.", "duration": 2},
                {"time": 29, "text": "Inhale... two... three... four.", "duration": 8},
                {"time": 37, "text": "Hold... two... three... four.", "duration": 8},
                {"time": 45, "text": "Exhale... two... three... four.", "duration": 8},
                {"time": 53, "text": "Hold... two... three... four.", "duration": 8},
                {"time": 61, "text": "Inhale... two... three... four.", "duration": 8},
                {"time": 69, "text": "Hold... two... three... four.", "duration": 8},
                {"time": 77, "text": "Exhale... two... three... four.", "duration": 8},
                {"time": 85, "text": "Hold... two... three... four.", "duration": 8},
                {"time": 93, "text": "Continue this rhythm on your own.", "duration": 3},
                {"time": 96, "text": "Let your breath find its natural pace.", "duration": 3},
                {"time": 99, "text": "In a moment, I'll guide you back.", "duration": 3},
                {"time": 102, "text": "Begin to deepen your breath slightly.", "duration": 3},
                {"time": 105, "text": "Wiggle your fingers and toes gently.", "duration": 3},
                {"time": 108, "text": "When you're ready, slowly open your eyes.", "duration": 3},
                {"time": 111, "text": "You've completed your Box Breathing session. Well done.", "duration": 3},
            ],
        },
        "script": [
            "Welcome to Box Breathing.",
            "Find a comfortable seated position. Close your eyes when ready.",
            "This technique balances your breath to calm your mind and body.",
            "We'll do four counts each: inhale, hold, exhale, hold.",
            "Let's practice one full cycle together, then continue on your own.",
            "Ready? Let's begin.",
            "[Guide user through 5-6 cycles with voice cues at each count]",
            "Continue this rhythm for 2-3 minutes.",
            "Let your breath find its natural pace.",
            "Begin to deepen your breath slightly.",
            "Wiggle your fingers and toes gently.",
            "When you're ready, slowly open your eyes.",
            "You've completed your Box Breathing session.",
        ],
    },
    {
        "id": "breathwork-478-intermediate",
        "title": "4-7-8 Relaxation Breath",
        "description": "Powerful parasympathetic activation: 4 count inhale, 7 hold, 8 exhale.",
        "duration_minutes": 8,
        "category": "breathwork",
        "level": "intermediate",
        "tags": ["stress-relief", "sleep-prep", "anxiety", "nervous-system"],
        "thumbnail_url": "/images/meditation/breathwork-478.jpg",
        "background_music": "/audio/music/ambient-deep-sleep-120bpm.mp3",
        "voice_guidance": {
            "speaker": "Marcus - Deep, Calming Male",
            "style": "measured, professional, grounding",
            "total_duration_seconds": 480,
            "segments": [
                {"time": 0, "text": "Welcome to the 4-7-8 Breathing technique.", "duration": 3},
                {"time": 3, "text": "This ancient yogic practice activates your relaxation response.", "duration": 4},
                {"time": 7, "text": "Sit with your spine straight. Let your shoulders relax.", "duration": 4},
                {"time": 11, "text": "Place the tip of your tongue against the ridge behind your upper teeth.", "duration": 4},
                {"time": 15, "text": "You'll keep it there throughout the entire practice.", "duration": 3},
                {"time": 18, "text": "Exhale completely through your mouth with a whoosh sound.", "duration": 3},
                {"time": 21, "text": "Now, let's do this together.", "duration": 2},
                {"time": 23, "text": "Close your mouth. Inhale through your nose for four counts.", "duration": 8},
                {"time": 31, "text": "Hold your breath for seven counts.", "duration": 10},
                {"time": 41, "text": "Exhale through your mouth for eight counts. Whoosh.", "duration": 10},
                {"time": 51, "text": "That's one complete cycle. Let's do four more.", "duration": 3},
                {"time": 54, "text": "Inhale for four...", "duration": 8},
                {"time": 62, "text": "Hold for seven...", "duration": 10},
                {"time": 72, "text": "Exhale for eight...", "duration": 10},
                {"time": 82, "text": "Again. Inhale for four...", "duration": 8},
                {"time": 90, "text": "Hold for seven...", "duration": 10},
                {"time": 100, "text": "Exhale for eight...", "duration": 10},
                {"time": 110, "text": "One more. Inhale for four...", "duration": 8},
                {"time": 118, "text": "Hold for seven...", "duration": 10},
                {"time": 128, "text": "Exhale for eight...", "duration": 10},
                {"time": 138, "text": "Last one. Inhale for four...", "duration": 8},
                {"time": 146, "text": "Hold for seven...", "duration": 10},
                {"time": 156, "text": "Exhale for eight...", "duration": 10},
                {"time": 166, "text": "Well done. Let your breath return to normal.", "duration": 3},
                {"time": 169, "text": "Notice the calm and stability spreading through your body.", "duration": 4},
                {"time": 173, "text": "This technique is yours to use whenever you need calm.", "duration": 4},
                {"time": 177, "text": "Begin to deepen your awareness of the present moment.", "duration": 3},
                {"time": 180, "text": "Gently open your eyes when ready.", "duration": 2},
                {"time": 182, "text": "Thank you for this practice.", "duration": 2},
            ],
        },
        "script": [
            "Welcome to 4-7-8 Breathing.",
            "This ancient technique activates your parasympathetic nervous system.",
            "Sit tall with shoulders relaxed.",
            "Place your tongue tip behind your upper front teeth.",
            "First, exhale completely through your mouth.",
            "Now inhale through your nose for 4 counts.",
            "Hold for 7 counts.",
            "Exhale through your mouth for 8 counts.",
            "Repeat this cycle 4 times total.",
            "After the final exhale, let your breath normalize.",
            "Rest and observe the calm.",
        ],
    },
    {
        "id": "breathwork-advanced-resonance",
        "title": "Resonant Breathing: Vagal Tone Training",
        "description": "Advanced 10-minute coherence breathing to optimize heart-rate variability.",
        "duration_minutes": 10,
        "category": "breathwork",
        "level": "advanced",
        "tags": ["heart-coherence", "nervous-system", "biohacking", "advanced"],
        "thumbnail_url": "/images/meditation/breathwork-resonance.jpg",
        "background_music": "/audio/music/binaural-coherence-60bpm.mp3",
        "voice_guidance": {
            "speaker": "Dr. Elena - Expert, Clear, Informative",
            "style": "scientific, precise, empowering",
            "total_duration_seconds": 600,
            "segments": [
                {"time": 0, "text": "Welcome to Resonant Breathing: Vagal Tone Training.", "duration": 4},
                {"time": 4, "text": "This practice optimizes your autonomic nervous system through synchronized breathing.", "duration": 5},
                {"time": 9, "text": "Research shows 5.5-6 breaths per minute creates optimal heart-rate variability.", "duration": 5},
                {"time": 14, "text": "Sit comfortably. You'll inhale for 5 seconds and exhale for 5 seconds.", "duration": 5},
                {"time": 19, "text": "This creates one 10-second breath cycle. Let's begin.", "duration": 3},
                {"time": 22, "text": "Inhale slowly through your nose for 5 seconds.", "duration": 7},
                {"time": 29, "text": "Exhale through your mouth for 5 seconds.", "duration": 7},
                {"time": 36, "text": "Continue at this pace. You're training coherence.", "duration": 3},
                {"time": 39, "text": "Feel your heart rate sync with your breath.", "duration": 3},
                {"time": 42, "text": "[Silence with soft music for 3 minutes while user maintains rhythm]", "duration": 180},
                {"time": 222, "text": "You're doing wonderfully. Maintain this steady rhythm.", "duration": 3},
                {"time": 225, "text": "[Silence for another 2 minutes]", "duration": 120},
                {"time": 345, "text": "Begin to gently deepen your breath.", "duration": 3},
                {"time": 348, "text": "Feel the relaxation and clarity you've cultivated.", "duration": 3},
                {"time": 351, "text": "This coherence will stay with you throughout your day.", "duration": 3},
                {"time": 354, "text": "Slowly open your eyes.", "duration": 2},
                {"time": 356, "text": "Thank you for this advanced practice.", "duration": 2},
            ],
        },
        "script": [
            "Welcome to Resonant Breathing Training.",
            "This optimizes your autonomic nervous system.",
            "We'll breathe at 5.5 breaths per minute - the coherence frequency.",
            "Inhale for 5 seconds, exhale for 5 seconds.",
            "This creates optimal heart-rate variability.",
            "[Continue for 10 minutes with silent periods interspersed with cues]",
            "You've trained your vagus nerve effectively.",
            "This coherence will remain with you.",
        ],
    },

    # ── BODY SCAN ───────────────────────────────────────────────────────────────
    {
        "id": "bodyscan-quick-beginner",
        "title": "Quick Body Scan (5 min)",
        "description": "Rapid progressive relaxation from head to toe for awareness and release.",
        "duration_minutes": 5,
        "category": "body-scan",
        "level": "beginner",
        "tags": ["quick", "relaxation", "awareness", "beginners"],
        "thumbnail_url": "/images/meditation/bodyscan-quick.jpg",
        "background_music": "/audio/music/soft-piano-ambient-80bpm.mp3",
        "voice_guidance": {
            "speaker": "Aria - Gentle, Nurturing Female",
            "style": "warm, inviting, reassuring",
            "total_duration_seconds": 300,
            "segments": [
                {"time": 0, "text": "Welcome to a quick body scan.", "duration": 2},
                {"time": 2, "text": "Lie down on your back in a comfortable position.", "duration": 3},
                {"time": 5, "text": "Let your feet fall open naturally. Let your arms rest at your sides.", "duration": 4},
                {"time": 9, "text": "Take a deep breath in through your nose.", "duration": 3},
                {"time": 12, "text": "And exhale through your mouth.", "duration": 3},
                {"time": 15, "text": "Now, bring your attention to the top of your head.", "duration": 2},
                {"time": 17, "text": "Notice any sensations. Release any tension.", "duration": 3},
                {"time": 20, "text": "Move down to your face and jaw.", "duration": 2},
                {"time": 22, "text": "Let your jaw relax. Soften your eyes.", "duration": 3},
                {"time": 25, "text": "Now your neck and shoulders.", "duration": 2},
                {"time": 27, "text": "Roll your shoulders back and down. Feel them melt into the floor.", "duration": 3},
                {"time": 30, "text": "Your chest and heart center.", "duration": 2},
                {"time": 32, "text": "Let your heart rate slow and steady.", "duration": 3},
                {"time": 35, "text": "Your belly and lower back.", "duration": 2},
                {"time": 37, "text": "With each exhale, release what you don't need.", "duration": 3},
                {"time": 40, "text": "Your hips, thighs, and knees.", "duration": 2},
                {"time": 42, "text": "Let them sink heavy and comfortable.", "duration": 3},
                {"time": 45, "text": "Your calves and feet.", "duration": 2},
                {"time": 47, "text": "Feel your whole body held by the earth beneath you.", "duration": 3},
                {"time": 50, "text": "Rest here for a moment in complete relaxation.", "duration": 5},
                {"time": 55, "text": "Begin to deepen your breath slowly.", "duration": 3},
                {"time": 58, "text": "Wiggle your fingers and toes.", "duration": 3},
                {"time": 61, "text": "Gently roll your head from side to side.", "duration": 3},
                {"time": 64, "text": "When you're ready, open your eyes.", "duration": 2},
                {"time": 66, "text": "Thank you for this practice.", "duration": 1},
            ],
        },
        "script": [
            "Welcome to a quick body scan.",
            "Lie on your back in a comfortable position.",
            "Let your body be fully supported.",
            "Bring awareness to your head - notice sensations, release tension.",
            "Move to face and jaw - soften your jaw.",
            "Shoulders - let them melt down.",
            "Chest - feel your heartbeat slow.",
            "Belly and lower back - exhale tension.",
            "Hips, thighs, knees - feel them sink and relax.",
            "Calves and feet - fully supported by the earth.",
            "Rest in complete body awareness.",
            "Gently return to movement and open your eyes.",
        ],
    },
    {
        "id": "bodyscan-deep-intermediate",
        "title": "Deep Body Scan (20 min)",
        "description": "Detailed progressive relaxation with 61-point focus for deep healing.",
        "duration_minutes": 20,
        "category": "body-scan",
        "level": "intermediate",
        "tags": ["relaxation", "healing", "sleep-prep", "detailed"],
        "thumbnail_url": "/images/meditation/bodyscan-deep.jpg",
        "background_music": "/audio/music/theta-waves-60bpm.mp3",
        "voice_guidance": {
            "speaker": "James - Calm, Authoritative Male",
            "style": "structured, detailed, grounding",
            "total_duration_seconds": 1200,
            "segments": [
                {"time": 0, "text": "Welcome to the Deep Body Scan meditation.", "duration": 3},
                {"time": 3, "text": "This 20-minute practice guides you through 61 points of awareness.", "duration": 4},
                {"time": 7, "text": "Find a quiet space where you won't be disturbed.", "duration": 3},
                {"time": 10, "text": "Lie on your back on a yoga mat or carpet.", "duration": 3},
                {"time": 13, "text": "Let your whole body be fully supported.", "duration": 3},
                {"time": 16, "text": "Close your eyes and take three deep breaths.", "duration": 5},
                {"time": 21, "text": "Now we begin the body scan. Bring awareness to your right big toe.", "duration": 4},
                {"time": 25, "text": "Notice any sensation - tingling, warmth, pressure. Nothing to fix.", "duration": 4},
                {"time": 29, "text": "Move to your right foot.", "duration": 2},
                {"time": 31, "text": "Right ankle, right calf, right shin.", "duration": 8},
                {"time": 39, "text": "Right knee, right thigh.", "duration": 6},
                {"time": 45, "text": "Right hip and right buttock.", "duration": 4},
                {"time": 49, "text": "Now move to the left side. Left big toe.", "duration": 3},
                {"time": 52, "text": "Left foot, ankle, calf, shin.", "duration": 8},
                {"time": 60, "text": "Left knee, thigh.", "duration": 5},
                {"time": 65, "text": "Left hip and buttock.", "duration": 4},
                {"time": 69, "text": "Now your lower back and sacrum.", "duration": 4},
                {"time": 73, "text": "Your belly and lower abdomen.", "duration": 4},
                {"time": 77, "text": "Your solar plexus and upper belly.", "duration": 4},
                {"time": 81, "text": "Your chest - feel your heart beating steadily.", "duration": 4},
                {"time": 85, "text": "Your upper back and mid-back.", "duration": 4},
                {"time": 89, "text": "Your shoulders - let them drop and relax.", "duration": 4},
                {"time": 93, "text": "Your right arm - shoulder to fingertips.", "duration": 6},
                {"time": 99, "text": "Your left arm - shoulder to fingertips.", "duration": 6},
                {"time": 105, "text": "Your neck - feel the support beneath it.", "duration": 4},
                {"time": 109, "text": "Your jaw - unclench it.", "duration": 3},
                {"time": 112, "text": "Your lips, mouth, and tongue.", "duration": 3},
                {"time": 115, "text": "Your nose and sinuses.", "duration": 3},
                {"time": 118, "text": "Your eyes - let them rest gently.", "duration": 3},
                {"time": 121, "text": "Your forehead and the space between your eyebrows.", "duration": 4},
                {"time": 125, "text": "The crown of your head.", "duration": 3},
                {"time": 128, "text": "Now feel your whole body at once.", "duration": 3},
                {"time": 131, "text": "From head to toe, you are completely relaxed.", "duration": 4},
                {"time": 135, "text": "Rest in this state for several minutes.", "duration": 30},
                {"time": 165, "text": "Begin to deepen your breath slowly.", "duration": 3},
                {"time": 168, "text": "Feel energy returning to your body.", "duration": 3},
                {"time": 171, "text": "Wiggle your fingers and toes gently.", "duration": 3},
                {"time": 174, "text": "When you're ready, slowly open your eyes.", "duration": 3},
                {"time": 177, "text": "Take a moment before you get up.", "duration": 2},
                {"time": 179, "text": "You've completed a deep body scan. Well done.", "duration": 1},
            ],
        },
        "script": [
            "Welcome to the Deep Body Scan.",
            "Lie comfortably on your back.",
            "Take three deep breaths to prepare.",
            "Bring awareness to right big toe - notice sensations without judgment.",
            "Progress through right foot, ankle, calf, shin, knee, thigh, hip, buttock.",
            "Repeat on left side with the same detailed attention.",
            "Move through lower back, belly, solar plexus.",
            "Chest - feel your heartbeat.",
            "Upper back, shoulders, arms, neck, jaw.",
            "Face - eyes, forehead, crown of head.",
            "Feel whole body awareness and complete relaxation.",
            "Rest in this state.",
            "Gradually return to full awareness and open your eyes.",
        ],
    },
    {
        "id": "bodyscan-yoga-nidra-advanced",
        "title": "Yoga Nidra: Deep Sleep & Recovery",
        "description": "45-minute advanced yoga nidra - 1 hour of sleep in full awareness.",
        "duration_minutes": 45,
        "category": "body-scan",
        "level": "advanced",
        "tags": ["sleep", "deep-rest", "subconscious", "advanced-healing"],
        "thumbnail_url": "/images/meditation/yoga-nidra.jpg",
        "background_music": "/audio/music/delta-waves-50bpm.mp3",
        "voice_guidance": {
            "speaker": "Swami - Traditional, Authoritative, Deeply Soothing",
            "style": "yogic, mystical, transformative",
            "total_duration_seconds": 2700,
            "segments": [
                {"time": 0, "text": "Welcome to Yoga Nidra - the yoga of sleep and conscious rest.", "duration": 4},
                {"time": 4, "text": "In this practice, your body will sleep while your consciousness remains aware.", "duration": 5},
                {"time": 9, "text": "Lie flat on your back in Savasana pose.", "duration": 3},
                {"time": 12, "text": "Let your feet fall open naturally.", "duration": 2},
                {"time": 14, "text": "Let your arms rest at your sides, palms facing up.", "duration": 3},
                {"time": 17, "text": "Close your eyes gently.", "duration": 2},
                {"time": 19, "text": "First, we set the Sankalpa - your conscious resolve.", "duration": 3},
                {"time": 22, "text": "Choose one short, positive intention. Something you want to embody or achieve.", "duration": 5},
                {"time": 27, "text": "Repeat it three times silently with deep conviction.", "duration": 4},
                {"time": 31, "text": "Now begin to observe your natural breath.", "duration": 3},
                {"time": 34, "text": "Don't control it - just watch it.", "duration": 3},
                {"time": 37, "text": "We begin body rotation of consciousness.", "duration": 2},
                {"time": 39, "text": "Bring awareness to your right hand. Feel it completely.", "duration": 4},
                {"time": 43, "text": "Right arm, right shoulder, right side of face.", "duration": 6},
                {"time": 49, "text": "Right ear, right nostril, right eye.", "duration": 4},
                {"time": 53, "text": "Now left side. Left hand to left eye in awareness.", "duration": 8},
                {"time": 61, "text": "Move through your entire body systematically.", "duration": 2},
                {"time": 63, "text": "Forehead, nose, mouth, chin, throat.", "duration": 6},
                {"time": 69, "text": "Heart center, solar plexus, belly, genitals.", "duration": 8},
                {"time": 77, "text": "Both legs, knees, ankles, feet completely.", "duration": 8},
                {"time": 85, "text": "Now experience pairs of opposites without judgment.", "duration": 3},
                {"time": 88, "text": "Feel heaviness... then lightness.", "duration": 8},
                {"time": 96, "text": "Heat... then coolness.", "duration": 8},
                {"time": 104, "text": "Contraction... then expansion.", "duration": 8},
                {"time": 112, "text": "Your body is dissolving into space.", "duration": 4},
                {"time": 116, "text": "You exist as pure consciousness.", "duration": 4},
                {"time": 120, "text": "Images begin to arise naturally. Watch them like clouds passing in the sky.", "duration": 5},
                {"time": 125, "text": "Don't cling to them. Don't push them away.", "duration": 4},
                {"time": 129, "text": "[Long silence for spontaneous visualization - 15 minutes]", "duration": 900},
                {"time": 1029, "text": "Gradually, awareness returns to your body.", "duration": 3},
                {"time": 1032, "text": "Feel your back against the earth.", "duration": 3},
                {"time": 1035, "text": "Recall your Sankalpa one final time.", "duration": 3},
                {"time": 1038, "text": "Repeat it with full commitment.", "duration": 4},
                {"time": 1042, "text": "Begin to deepen your breath.", "duration": 3},
                {"time": 1045, "text": "Wiggle your fingers and toes very gently.", "duration": 4},
                {"time": 1049, "text": "Stretch your arms overhead slowly.", "duration": 3},
                {"time": 1052, "text": "Roll your head slowly from side to side.", "duration": 3},
                {"time": 1055, "text": "Slowly, gently, bring yourself back to waking awareness.", "duration": 4},
                {"time": 1059, "text": "Open your eyes when ready.", "duration": 2},
                {"time": 1061, "text": "Lie still for a moment before sitting up.", "duration": 3},
                {"time": 1064, "text": "You have completed Yoga Nidra. Integration begins now.", "duration": 2},
            ],
        },
        "script": [
            "Welcome to Yoga Nidra - conscious sleep.",
            "Lie in Savasana. Your body sleeps; your mind remains aware.",
            "Set your Sankalpa - a short positive intention. Repeat three times.",
            "Observe your natural breath without control.",
            "Rotate consciousness through your entire body systematically.",
            "Experience pairs of opposites - heaviness/lightness, heat/coolness.",
            "Your body dissolves into space. You are pure consciousness.",
            "Images arise and dissolve naturally. Witness them without attachment.",
            "Rest in this state of deep awareness.",
            "Gradually recall your Sankalpa with full commitment.",
            "Deepen your breath and gently return to physical awareness.",
            "Open your eyes slowly.",
            "You have received the benefits of 1+ hours of sleep.",
        ],
    },

    # ── VISUALIZATION ───────────────────────────────────────────────────────────
    {
        "id": "visualization-morning-beginner",
        "title": "Morning Intention & Visualization",
        "description": "Set your day's direction with clarity and positive energy.",
        "duration_minutes": 5,
        "category": "visualization",
        "level": "beginner",
        "tags": ["morning", "intention", "focus", "energy"],
        "thumbnail_url": "/images/meditation/morning-intention.jpg",
        "background_music": "/audio/music/uplifting-morning-100bpm.mp3",
        "voice_guidance": {
            "speaker": "Luna - Bright, Energetic Female",
            "style": "inspiring, clear, empowering",
            "total_duration_seconds": 300,
            "segments": [
                {"time": 0, "text": "Good morning. Let's set your intention for today.", "duration": 3},
                {"time": 3, "text": "Sit upright with your spine tall and straight.", "duration": 3},
                {"time": 6, "text": "Plant your feet firmly on the ground.", "duration": 2},
                {"time": 8, "text": "Take five deep, energizing breaths.", "duration": 8},
                {"time": 16, "text": "Now, close your eyes and visualize your ideal day unfolding.", "duration": 3},
                {"time": 19, "text": "See yourself moving through your day with ease and confidence.", "duration": 4},
                {"time": 23, "text": "Imagine yourself handling challenges with grace and clarity.", "duration": 4},
                {"time": 27, "text": "Visualize interactions with people being warm and meaningful.", "duration": 4},
                {"time": 31, "text": "See yourself ending your day feeling accomplished and peaceful.", "duration": 4},
                {"time": 35, "text": "Now, choose one word or quality to embody today.", "duration": 4},
                {"time": 39, "text": "It might be: Calm, Strength, Joy, Clarity, or Love.", "duration": 4},
                {"time": 43, "text": "Feel this quality becoming alive within you.", "duration": 3},
                {"time": 46, "text": "Repeat it three times silently with conviction.", "duration": 5},
                {"time": 51, "text": "Hold this feeling in your heart.", "duration": 3},
                {"time": 54, "text": "Take one final deep breath.", "duration": 3},
                {"time": 57, "text": "Open your eyes, carrying this energy into your day.", "duration": 3},
                {"time": 60, "text": "You are ready. Go create your day with intention.", "duration": 2},
            ],
        },
        "script": [
            "Good morning. Let's set your intention.",
            "Sit tall with feet planted firmly.",
            "Take five deep, energizing breaths.",
            "Close your eyes and visualize your ideal day.",
            "See yourself moving with ease and confidence.",
            "Imagine handling challenges with grace.",
            "Visualize warm, meaningful interactions.",
            "See yourself ending peacefully and accomplished.",
            "Choose one quality to embody: Calm, Strength, Joy, Clarity, Love.",
            "Feel this quality come alive within you.",
            "Repeat it three times with conviction.",
            "Open your eyes and carry this into your day.",
        ],
    },
    {
        "id": "visualization-chakra-intermediate",
        "title": "7 Chakra Activation & Balancing",
        "description": "Journey through all 7 chakras with color, sound, and visualization.",
        "duration_minutes": 22,
        "category": "visualization",
        "level": "intermediate",
        "tags": ["chakras", "energy", "healing", "spiritual"],
        "thumbnail_url": "/images/meditation/chakras.jpg",
        "background_music": "/audio/music/binaural-chakra-healing-100bpm.mp3",
        "voice_guidance": {
            "speaker": "Indra - Mystical, Experienced Female",
            "style": "spiritual, poetic, visionary",
            "total_duration_seconds": 1320,
            "segments": [
                {"time": 0, "text": "Welcome to the 7 Chakra Activation meditation.", "duration": 4},
                {"time": 4, "text": "Chakras are energy centers that regulate all life functions.", "duration": 4},
                {"time": 8, "text": "Today, we'll visit each one, awakening and balancing them.", "duration": 4},
                {"time": 12, "text": "Sit cross-legged or in easy pose. Spine tall and straight.", "duration": 4},
                {"time": 16, "text": "Ground your energy deep into the earth beneath you.", "duration": 3},
                {"time": 19, "text": "We begin with the Root Chakra - Muladhara - at the base of your spine.", "duration": 4},
                {"time": 23, "text": "Visualize a deep red glowing sphere of light.", "duration": 3},
                {"time": 26, "text": "This chakra is your foundation, your stability, your home.", "duration": 4},
                {"time": 30, "text": "Chant LAM silently. Feel the root chakra awaken.", "duration": 8},
                {"time": 38, "text": "Move up to the Sacral Chakra - Svadhishthana - below your navel.", "duration": 4},
                {"time": 42, "text": "Visualize a warm orange light spiraling and flowing.", "duration": 3},
                {"time": 45, "text": "This is your creative center, your passion, your flow.", "duration": 4},
                {"time": 49, "text": "Chant VAM. Feel creativity awakening.", "duration": 8},
                {"time": 57, "text": "Up to the Solar Plexus - Manipura - at your belly button.", "duration": 4},
                {"time": 61, "text": "Visualize bright golden light, like a personal sun.", "duration": 3},
                {"time": 64, "text": "This is your power center, your will, your radiance.", "duration": 4},
                {"time": 68, "text": "Chant RAM. Feel your inner fire ignite.", "duration": 8},
                {"time": 76, "text": "Move to the Heart Chakra - Anahata - at the center of your chest.", "duration": 4},
                {"time": 80, "text": "Visualize a glowing green or pink light, infinite and loving.", "duration": 3},
                {"time": 83, "text": "This is your bridge between body and spirit, your capacity to love.", "duration": 4},
                {"time": 87, "text": "Chant YAM. Feel your heart opening and expanding.", "duration": 8},
                {"time": 95, "text": "Up to the Throat Chakra - Vishuddha - at your throat.", "duration": 4},
                {"time": 99, "text": "Visualize a bright blue light, clear and crystalline.", "duration": 3},
                {"time": 102, "text": "This is your truth center, your authentic expression.", "duration": 4},
                {"time": 106, "text": "Chant HAM. Feel your voice becoming clearer and more powerful.", "duration": 8},
                {"time": 114, "text": "Move to the Third Eye - Ajna - between your eyebrows.", "duration": 4},
                {"time": 118, "text": "Visualize indigo light, deep and mysterious.", "duration": 3},
                {"time": 121, "text": "This is your intuition center, your inner vision, your wisdom.", "duration": 4},
                {"time": 125, "text": "Chant OM. Feel your intuition becoming sharper.", "duration": 8},
                {"time": 133, "text": "Finally, the Crown Chakra - Sahasrara - at the top of your head.", "duration": 4},
                {"time": 137, "text": "Visualize white or violet light, opening upward to infinity.", "duration": 4},
                {"time": 141, "text": "This is your connection to the universe, to oneness.", "duration": 4},
                {"time": 145, "text": "Chant OM. Feel yourself connected to all existence.", "duration": 8},
                {"time": 153, "text": "Now, see all seven chakras glowing and spinning in harmony.", "duration": 4},
                {"time": 157, "text": "Energy flows freely up and down your central channel.", "duration": 4},
                {"time": 161, "text": "You are balanced, clear, radiant, and whole.", "duration": 4},
                {"time": 165, "text": "Rest in this integrated state for a moment.", "duration": 30},
                {"time": 195, "text": "Slowly return your awareness to the room.", "duration": 3},
                {"time": 198, "text": "Feel your body becoming heavier and more grounded.", "duration": 3},
                {"time": 201, "text": "Gently open your eyes.", "duration": 2},
                {"time": 203, "text": "You've balanced all seven chakras. Feel this throughout your day.", "duration": 2},
            ],
        },
        "script": [
            "Welcome to 7 Chakra Activation.",
            "Chakras are energy centers regulating all life functions.",
            "Sit upright. Ground your energy deeply.",
            "Root Chakra (red, LAM): Foundation, stability.",
            "Sacral Chakra (orange, VAM): Creativity, flow.",
            "Solar Plexus (yellow, RAM): Power, will, radiance.",
            "Heart Chakra (green/pink, YAM): Love, compassion.",
            "Throat Chakra (blue, HAM): Truth, authentic expression.",
            "Third Eye (indigo, OM): Intuition, inner vision.",
            "Crown Chakra (white/violet, OM): Oneness, connection.",
            "See all chakras glowing and spinning in harmony.",
            "Feel integrated, clear, and radiant.",
            "Slowly return to the room and open your eyes.",
        ],
    },
    {
        "id": "visualization-future-self-advanced",
        "title": "Meet Your Future Self: Life Design Visualization",
        "description": "Advanced guided journey to your highest potential self and life vision.",
        "duration_minutes": 30,
        "category": "visualization",
        "level": "advanced",
        "tags": ["manifestation", "life-design", "advanced", "transformation"],
        "thumbnail_url": "/images/meditation/future-self.jpg",
        "background_music": "/audio/music/expansive-vision-80bpm.mp3",
        "voice_guidance": {
            "speaker": "Oracle - Deep, Wise, Transformative",
            "style": "visionary, profound, empowering",
            "total_duration_seconds": 1800,
            "segments": [
                {"time": 0, "text": "Welcome to a deep visualization of your future self.", "duration": 4},
                {"time": 4, "text": "Find a quiet, comfortable place where you can rest undisturbed.", "duration": 4},
                {"time": 8, "text": "Lie down or sit comfortably with your spine supported.", "duration": 3},
                {"time": 11, "text": "Close your eyes and begin breathing deeply.", "duration": 3},
                {"time": 14, "text": "We're going to travel forward in time - 5, 10, or even 20 years.", "duration": 4},
                {"time": 18, "text": "Imagine yourself living a life aligned with your highest vision.", "duration": 4},
                {"time": 22, "text": "First, notice where you live. What does your environment look like?", "duration": 5},
                {"time": 27, "text": "Is it peaceful? Beautiful? How does it feel to be there?", "duration": 4},
                {"time": 31, "text": "Now notice the people around you. Who is in your life?", "duration": 4},
                {"time": 35, "text": "What kind of relationships do you have?", "duration": 3},
                {"time": 38, "text": "Feel the warmth and love in your connections.", "duration": 4},
                {"time": 42, "text": "Move your awareness to your work and purpose.", "duration": 3},
                {"time": 45, "text": "What are you doing? How are you contributing to the world?", "duration": 4},
                {"time": 49, "text": "Feel the satisfaction and fulfillment this brings you.", "duration": 4},
                {"time": 53, "text": "Notice your physical self. How do you feel in your body?", "duration": 4},
                {"time": 57, "text": "Healthy, strong, vital, and vibrant.", "duration": 3},
                {"time": 60, "text": "Look at your future self's face. Who are you becoming?", "duration": 4},
                {"time": 64, "text": "What wisdom, peace, and joy are reflected in your eyes?", "duration": 4},
                {"time": 68, "text": "Now, imagine this future self turning to face you.", "duration": 3},
                {"time": 71, "text": "They smile at you with recognition and encouragement.", "duration": 3},
                {"time": 74, "text": "They step forward and embrace you.", "duration": 3},
                {"time": 77, "text": "Feel their presence. Feel their knowing.", "duration": 3},
                {"time": 80, "text": "They begin to share a message with you.", "duration": 2},
                {"time": 82, "text": "What wisdom do they want you to know?", "duration": 5},
                {"time": 87, "text": "[Silent space for intuitive reception]", "duration": 60},
                {"time": 147, "text": "They give you a gift - something you need on your journey.", "duration": 3},
                {"time": 150, "text": "[Silent space for receiving]", "duration": 30},
                {"time": 180, "text": "Your future self dissolves into light.", "duration": 3},
                {"time": 183, "text": "This light enters your heart and merges with your being.", "duration": 4},
                {"time": 187, "text": "You now carry their wisdom, their vision, their knowing.", "duration": 4},
                {"time": 191, "text": "Slowly begin to return to your present body.", "duration": 3},
                {"time": 194, "text": "Feel yourself back in the room, in this moment.", "duration": 3},
                {"time": 197, "text": "Wiggle your fingers and toes gently.", "duration": 3},
                {"time": 200, "text": "Open your eyes slowly.", "duration": 2},
                {"time": 202, "text": "The vision of your highest self is now activated within you.", "duration": 2},
                {"time": 204, "text": "You are on your way.", "duration": 1},
            ],
        },
        "script": [
            "Welcome to Future Self Visualization.",
            "Travel forward in time to your fully realized self.",
            "Notice where you live - environment and feeling.",
            "Who is in your life? Feel the love and connections.",
            "What is your work and purpose? Feel the fulfillment.",
            "How is your health and physical vitality?",
            "Look at your future self's face - the wisdom there.",
            "Your future self turns and embraces you.",
            "Receive their message - what wisdom do they share?",
            "Accept their gift - what do you need?",
            "Your future self becomes light that merges with your heart.",
            "You carry their vision and knowing within you.",
            "Return slowly to the present moment.",
            "You are now aligned with your highest potential.",
        ],
    },

    # ── MANTRA ─────────────────────────────────────────────────────────────────
    {
        "id": "mantra-om-beginner",
        "title": "Sacred OM Chanting",
        "description": "Simple mantra meditation using the universal sound OM.",
        "duration_minutes": 10,
        "category": "mantra",
        "level": "beginner",
        "tags": ["mantra", "sacred-sound", "beginner", "universal"],
        "thumbnail_url": "/images/meditation/om-mantra.jpg",
        "background_music": "/audio/music/om-frequency-108hz.mp3",
        "voice_guidance": {
            "speaker": "Vedic Scholar - Authentic Sanskrit",
            "style": "traditional, reverent, clear",
            "total_duration_seconds": 600,
            "segments": [
                {"time": 0, "text": "Welcome to OM mantra meditation.", "duration": 3},
                {"time": 3, "text": "OM is the universal sound, the vibration of creation itself.", "duration": 4},
                {"time": 7, "text": "Sit comfortably with your spine tall.", "duration": 2},
                {"time": 9, "text": "Let your hands rest on your knees, palms up.", "duration": 3},
                {"time": 12, "text": "Close your eyes and take three deep breaths.", "duration": 5},
                {"time": 17, "text": "Now, I'll chant OM three times. Listen and feel the vibration.", "duration": 3},
                {"time": 20, "text": "OOOOOMMMMMMM", "duration": 8},
                {"time": 28, "text": "OOOOOMMMMMMM", "duration": 8},
                {"time": 36, "text": "OOOOOMMMMMMM", "duration": 8},
                {"time": 44, "text": "Now, you'll chant OM with me.", "duration": 2},
                {"time": 46, "text": "Inhale deeply through your nose.", "duration": 3},
                {"time": 49, "text": "Exhale slowly while chanting: OOOOOMMMMMMM", "duration": 10},
                {"time": 59, "text": "Inhale again.", "duration": 3},
                {"time": 62, "text": "Exhale: OOOOOMMMMMMM", "duration": 10},
                {"time": 72, "text": "Once more: OOOOOMMMMMMM", "duration": 10},
                {"time": 82, "text": "Now continue chanting OM on your own.", "duration": 2},
                {"time": 84, "text": "One breath, one OM. Feel the vibration.", "duration": 2},
                {"time": 86, "text": "[Soft OM chanting in background for user to join]", "duration": 240},
                {"time": 326, "text": "Begin to slow your chanting.", "duration": 3},
                {"time": 329, "text": "Longer breaths, deeper OMs.", "duration": 3},
                {"time": 332, "text": "One final OM.", "duration": 3},
                {"time": 335, "text": "OOOOOMMMMMMM", "duration": 8},
                {"time": 343, "text": "Let the vibration continue to resonate within you.", "duration": 3},
                {"time": 346, "text": "Rest in silence for a moment.", "duration": 10},
                {"time": 356, "text": "Slowly open your eyes.", "duration": 2},
                {"time": 358, "text": "You've chanted the sound of creation.", "duration": 1},
            ],
        },
        "script": [
            "Welcome to OM mantra meditation.",
            "OM is the universal sound of creation.",
            "Sit tall with hands on knees, palms up.",
            "Close your eyes and take three deep breaths.",
            "Listen as I chant OM three times.",
            "Feel the vibration throughout your being.",
            "Now we'll chant together.",
            "Inhale deeply, exhale while chanting OOOOOMMMMMMM.",
            "Repeat this rhythm 3-4 times.",
            "Then continue on your own - one breath, one OM.",
            "Feel the sacred vibration.",
            "Gradually slow and deepen your OMs.",
            "Rest in the silence after your final OM.",
            "Slowly open your eyes.",
        ],
    },
    {
        "id": "mantra-loving-kindness-intermediate",
        "title": "Loving-Kindness (Metta) Mantra",
        "description": "Transform your heart with the traditional Metta practice and mantras.",
        "duration_minutes": 18,
        "category": "mantra",
        "level": "intermediate",
        "tags": ["compassion", "mantra", "heart-opening", "emotional-healing"],
        "thumbnail_url": "/images/meditation/metta-mantra.jpg",
        "background_music": "/audio/music/heart-chakra-binaural-100hz.mp3",
        "voice_guidance": {
            "speaker": "Bhikkhu - Buddhist Monk, Warm and Wise",
            "style": "compassionate, ancient, gentle",
            "total_duration_seconds": 1080,
            "segments": [
                {"time": 0, "text": "Welcome to Loving-Kindness meditation.", "duration": 3},
                {"time": 3, "text": "Metta, or loving-kindness, is a practice of cultivating universal compassion.", "duration": 5},
                {"time": 8, "text": "Sit comfortably with your hand on your heart.", "duration": 3},
                {"time": 11, "text": "Feel your heartbeat beneath your palm.", "duration": 3},
                {"time": 14, "text": "Close your eyes and breathe naturally.", "duration": 3},
                {"time": 17, "text": "First, we send loving-kindness to ourselves.", "duration": 3},
                {"time": 20, "text": "Repeat silently: May I be happy.", "duration": 4},
                {"time": 24, "text": "May I be healthy.", "duration": 3},
                {"time": 27, "text": "May I be safe.", "duration": 3},
                {"time": 30, "text": "May I live with ease.", "duration": 3},
                {"time": 33, "text": "Feel the warmth in your heart growing.", "duration": 3},
                {"time": 36, "text": "Repeat these four phrases again, slowly.", "duration": 2},
                {"time": 38, "text": "May I be happy. May I be healthy. May I be safe. May I live with ease.", "duration": 12},
                {"time": 50, "text": "Now, bring to mind someone you love deeply.", "duration": 3},
                {"time": 53, "text": "Send them the same loving-kindness.", "duration": 2},
                {"time": 55, "text": "May you be happy. May you be healthy. May you be safe. May you live with ease.", "duration": 10},
                {"time": 65, "text": "Expand to a neutral person - someone you don't know well.", "duration": 3},
                {"time": 68, "text": "May you be happy. May you be healthy. May you be safe. May you live with ease.", "duration": 10},
                {"time": 78, "text": "Now, bring to mind someone difficult - someone who challenges you.", "duration": 4},
                {"time": 82, "text": "This takes courage, but we send them loving-kindness too.", "duration": 3},
                {"time": 85, "text": "May you be happy. May you be healthy. May you be safe. May you live with ease.", "duration": 10},
                {"time": 95, "text": "Finally, expand this loving-kindness to all beings everywhere.", "duration": 4},
                {"time": 99, "text": "May all beings be happy. May all beings be healthy.", "duration": 6},
                {"time": 105, "text": "May all beings be safe. May all beings live with ease.", "duration": 6},
                {"time": 111, "text": "Feel this wave of compassion spreading across the entire world.", "duration": 4},
                {"time": 115, "text": "Rest in the warmth of an open heart.", "duration": 20},
                {"time": 135, "text": "Bring your awareness back to your breath.", "duration": 3},
                {"time": 138, "text": "Feel your feet on the ground.", "duration": 3},
                {"time": 141, "text": "Slowly open your eyes.", "duration": 2},
                {"time": 143, "text": "Carry this loving-kindness with you throughout your day.", "duration": 2},
            ],
        },
        "script": [
            "Welcome to Loving-Kindness meditation.",
            "Metta means loving-kindness - cultivating universal compassion.",
            "Sit with your hand on your heart.",
            "First, send loving-kindness to yourself:",
            "May I be happy. May I be healthy. May I be safe. May I live with ease.",
            "Feel the warmth growing in your heart.",
            "Now bring someone you love to mind.",
            "Send them the same phrases.",
            "Expand to a neutral person - someone you don't know well.",
            "Now, someone difficult - someone who challenges you.",
            "Finally, all beings everywhere.",
            "May all beings be happy, healthy, safe, and live with ease.",
            "Rest in the warmth of an open heart.",
            "Slowly return and open your eyes.",
        ],
    },
    {
        "id": "mantra-so-hum-advanced",
        "title": "SO-HUM: The Self-Inquiry Mantra",
        "description": "Advanced yoga mantra for self-realization and dissolution of ego boundaries.",
        "duration_minutes": 26,
        "category": "mantra",
        "level": "advanced",
        "tags": ["self-inquiry", "mantra", "non-dual", "advanced-spiritual"],
        "thumbnail_url": "/images/meditation/so-hum-mantra.jpg",
        "background_music": "/audio/music/monochord-heart-chakra-80hz.mp3",
        "voice_guidance": {
            "speaker": "Advaita Master - Ancient, Transcendent",
            "style": "non-dual, profoundly deep, liberating",
            "total_duration_seconds": 1560,
            "segments": [
                {"time": 0, "text": "Welcome to SO-HUM: the mantra of self-recognition.", "duration": 4},
                {"time": 4, "text": "SO-HUM means 'I am That' - the recognition that you are the universal consciousness.", "duration": 5},
                {"time": 9, "text": "This is a practice of self-inquiry and non-dual realization.", "duration": 4},
                {"time": 13, "text": "Find a quiet space where you can sit undisturbed for 26 minutes.", "duration": 4},
                {"time": 17, "text": "Sit in a meditation posture with your spine naturally straight.", "duration": 3},
                {"time": 20, "text": "Close your eyes and release all effort.", "duration": 3},
                {"time": 23, "text": "Begin observing your natural breath without controlling it.", "duration": 4},
                {"time": 27, "text": "As you inhale, silently chant SO.", "duration": 3},
                {"time": 30, "text": "As you exhale, silently chant HUM.", "duration": 3},
                {"time": 33, "text": "SO on the inhale, HUM on the exhale.", "duration": 3},
                {"time": 36, "text": "Let the mantra merge with your breath.", "duration": 3},
                {"time": 39, "text": "SO (inhale)... HUM (exhale)... SO (inhale)... HUM (exhale)...", "duration": 10},
                {"time": 49, "text": "Continue this rhythm effortlessly.", "duration": 2},
                {"time": 51, "text": "[Long silence for autonomous practice - 15 minutes]", "duration": 900},
                {"time": 951, "text": "Begin to release the mantra gradually.", "duration": 3},
                {"time": 954, "text": "Let it dissolve into the silence from which it came.", "duration": 4},
                {"time": 958, "text": "Rest in the stillness between breaths.", "duration": 3},
                {"time": 961, "text": "Who is the one observing the breath?", "duration": 3},
                {"time": 964, "text": "Who is aware of the silence?", "duration": 3},
                {"time": 967, "text": "There is no separation between observer and observed.", "duration": 4},
                {"time": 971, "text": "You are That which witnesses all.", "duration": 3},
                {"time": 974, "text": "SO-HUM. I am That.", "duration": 3},
                {"time": 977, "text": "Rest in this recognition.", "duration": 20},
                {"time": 997, "text": "Gradually become aware of your body sitting in space.", "duration": 3},
                {"time": 1000, "text": "Feel your feet touching the earth.", "duration": 3},
                {"time": 1003, "text": "Feel your spine supporting your being.", "duration": 3},
                {"time": 1006, "text": "Begin to deepen your breath slowly.", "duration": 3},
                {"time": 1009, "text": "When you're ready, open your eyes.", "duration": 2},
                {"time": 1011, "text": "You are That. You have always been That.", "duration": 2},
                {"time": 1013, "text": "The recognition never leaves you.", "duration": 1},
            ],
        },
        "script": [
            "Welcome to SO-HUM meditation.",
            "SO-HUM means 'I am That' - the universal consciousness within you.",
            "Sit with spine straight in a comfortable posture.",
            "Close your eyes and observe your natural breath.",
            "As you inhale, silently chant SO.",
            "As you exhale, silently chant HUM.",
            "SO (inhale), HUM (exhale).",
            "Let the mantra merge with your breath.",
            "Continue effortlessly for 15+ minutes.",
            "Gradually release the mantra into silence.",
            "Rest in the awareness that witnesses all.",
            "You are That - the unchanging consciousness.",
            "Slowly return to body awareness.",
            "Open your eyes knowing: I am That.",
        ],
    },
]

CATEGORY_MAP: dict[str, list[str]] = {
    "breathwork": ["breathwork-box-beginner", "breathwork-478-intermediate", "breathwork-advanced-resonance"],
    "body-scan": ["bodyscan-quick-beginner", "bodyscan-deep-intermediate", "bodyscan-yoga-nidra-advanced"],
    "visualization": ["visualization-morning-beginner", "visualization-chakra-intermediate", "visualization-future-self-advanced"],
    "mantra": ["mantra-om-beginner", "mantra-loving-kindness-intermediate", "mantra-so-hum-advanced"],
}


class MeditationService:
    def _resolve_guide_ids(self, guide_ids: list[str]) -> list[dict[str, Any]]:
        return [guide for guide_id in guide_ids if (guide := self.get_guide(guide_id))]

    def get_all_guides(self) -> list[dict[str, Any]]:
        return MEDITATION_GUIDES

    def get_guide(self, guide_id: str) -> dict[str, Any] | None:
        return next((g for g in MEDITATION_GUIDES if g["id"] == guide_id), None)

    def get_by_category(self, category: str) -> list[dict[str, Any]]:
        ordered_ids = CATEGORY_MAP.get(category, [])
        if ordered_ids:
            return self._resolve_guide_ids(ordered_ids)
        return [g for g in MEDITATION_GUIDES if g["category"] == category]

    def get_by_level(self, level: str) -> list[dict[str, Any]]:
        return [g for g in MEDITATION_GUIDES if g["level"] == level]

    def get_by_category_and_level(self, category: str, level: str) -> list[dict[str, Any]]:
        return [g for g in self.get_by_category(category) if g["level"] == level]

    def get_by_tag(self, tag: str) -> list[dict[str, Any]]:
        return [g for g in MEDITATION_GUIDES if tag.lower() in [t.lower() for t in g["tags"]]]

    def get_voice_guidance(self, guide_id: str) -> dict[str, Any] | None:
        guide = self.get_guide(guide_id)
        return guide.get("voice_guidance") if guide else None

    def get_voice_segments(self, guide_id: str) -> list[dict[str, Any]] | None:
        guidance = self.get_voice_guidance(guide_id)
        return guidance.get("segments") if guidance else None

    def recommend_for_profile(self, profile: dict[str, Any]) -> list[dict[str, Any]]:
        """Rule-based recommendation enriched by Nexus guide_engine mental-state mapping."""
        goals = profile.get("health_goals") or []
        mental_state = (profile.get("mental_state") or "").lower()
        recommended_ids: set[str] = set()

        mental_state_map: dict[str, set[str]] = {
            "sleep": {"bodyscan-yoga-nidra-advanced", "mantra-om-beginner"},
            "rest": {"bodyscan-quick-beginner", "breathwork-478-intermediate"},
            "stress": {"breathwork-478-intermediate", "mantra-loving-kindness-intermediate"},
            "anxiety": {"breathwork-478-intermediate", "mantra-loving-kindness-intermediate"},
            "spiritual": {"visualization-chakra-intermediate", "mantra-so-hum-advanced"},
            "focus": {"breathwork-box-beginner", "visualization-morning-beginner"},
            "energy": {"visualization-morning-beginner", "breathwork-box-beginner"},
            "burnout": {"bodyscan-quick-beginner", "breathwork-advanced-resonance"},
            "neutral": {"breathwork-box-beginner", "visualization-morning-beginner"},
        }

        for state, ids in mental_state_map.items():
            if state in mental_state:
                recommended_ids.update(ids)

        try:
            from app.nexus_core.guide_engine import select_meditation_style
            nexus_style = select_meditation_style(mental_state)
            nexus_style_map: dict[str, set[str]] = {
                "mindfulness": {"breathwork-box-beginner", "visualization-morning-beginner"},
                "mantra": {"mantra-loving-kindness-intermediate", "mantra-om-beginner"},
                "body_scan": {"bodyscan-quick-beginner", "bodyscan-deep-intermediate"},
                "visualization": {"visualization-morning-beginner", "visualization-future-self-advanced"},
            }
            recommended_ids.update(nexus_style_map.get(nexus_style, set()))
        except Exception:
            pass

        for goal in goals:
            goal_lower = goal.lower()
            if "sleep" in goal_lower or "rest" in goal_lower:
                recommended_ids.update({"bodyscan-yoga-nidra-advanced", "mantra-om-beginner"})
            if "stress" in goal_lower or "anxiety" in goal_lower or "relax" in goal_lower:
                recommended_ids.update({"breathwork-478-intermediate", "mantra-loving-kindness-intermediate", "bodyscan-quick-beginner"})
            if "energy" in goal_lower or "morning" in goal_lower or "focus" in goal_lower:
                recommended_ids.update({"visualization-morning-beginner", "breathwork-box-beginner"})
            if "spiritual" in goal_lower or "chakra" in goal_lower or "inner" in goal_lower:
                recommended_ids.update({"visualization-chakra-intermediate", "mantra-so-hum-advanced"})
            if "balance" in goal_lower or "wellness" in goal_lower:
                recommended_ids.update({"breathwork-box-beginner", "visualization-morning-beginner", "bodyscan-quick-beginner"})

        if not recommended_ids:
            recommended_ids = {"breathwork-box-beginner", "visualization-morning-beginner", "mantra-loving-kindness-intermediate"}

        return [g for g in MEDITATION_GUIDES if g["id"] in recommended_ids]

    def get_nexus_daily_guide(self, mental_state: str, goal: str,
                               preferred_style: str | None = None) -> dict[str, Any]:
        """Generate a full Nexus daily guide (meditation + breathing + meals)."""
        try:
            from app.nexus_core.guide_engine import generate_guide
            return generate_guide(mental_state=mental_state, goal=goal,
                                  preferred_meditation_style=preferred_style)
        except Exception as exc:
            return {"error": str(exc), "meditation_style": "mindfulness"}


meditation_service = MeditationService()
